### ISSUE TITLE
ONS-International-exports-of-services-from-subnational-areas-of-the-UK

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#24] opened 2020-03-16 13:21 UTC

**Comment by LPerryman** [comment] 2020-03-31 14:53
Due to the difference in definition for regions NUTS1, NUTS2, NUTS3 and then joint authority that has not code i think this should be split into 2 datasets:
1. Tabs 1a, 2b, 2a, 3b, 3. Service Origin Geography should be changed to NUTS Geography 
2. Tabs 4a, 4b Service Origin Geography should stay the same

**Comment by LPerryman** [comment] 2020-04-01 13:47
Darren has contacted someone and asked if codes are available for the Areas in table 4a and 4b. On stop until he gets a reply

**Comment by LPerryman** [comment] 2020-04-06 08:35
Data has been split as mentioned above into 2 datasets as no codes are available for some of the defined sub regions

**Comment by LPerryman** [comment] 2020-04-06 10:07
- [ ] Does the dataset show up or is there an error?
- [ ] Is it in the list of datasets from the main page?
- [ ] Is there descriptive metadata on the search page?
- [ ] Does transformed info match the original?
- [ ] Does the tidydata download show all the data?
- [ ] Note differences in column/row headers
- [ ] Are there multiple cubes? List titles of cubes 
- [ ] What needs differentiating? Totals - Nothing
- [ ] Are there titles that need harmonising? World/Worldwide 
- [ ] Does the structure look sensible? 
- [ ] Does the hierarchy work?
- [ ] What needs further investigation or context? 
- [ ] Any duplications?
- [ ] List any detailed metadata/methodology to add retrospectively 
- [ ] Short metadata added

**Comment by LPerryman** [comment] 2020-04-06 10:29
Data not currently showing in PMD4
Names of the areas rather than the codes are showing
Down load fails, only one row in csv
2 Cubes, one with NUTs codes and one with Joint Authority areas
Need to add explanationd of NUTS and what the Joint Authorities are for

**Comment by LPerryman** [comment] 2020-04-06 10:53
Metadata added to description and comments of trig files

**Comment by IeuanMan** [comment] 2020-04-08 13:20
@Tracey-B 

https://docs.google.com/document/d/1dBW5fMtl1A5d50rLIhhgsire6TmVJc793Madn-FiEmM/edit

BA Quality Assurance High Level Checks 
Dataset: International exports of services from subnational areas of the UK
Completed by: Tracey Burgess
Date: 06/04/2020
PMD V4
Is the dataset listed  in PMD v4 staging?
No
Does the dataset open?


Is there descriptive metadata on the PMD v4 staging landing page?


Does transformed info seem to match the original?


Contents Modified Date


PMD V3
Is the dataset listed  in PMD V3?
Yes Twice 
Does the dataset open?
Yes both 
Is there descriptive metadata on the PMD v3 landing page?
Yes 
Modified Date
26/03/2020 & 26/04/2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
Yes*
Does the structure look sensible?
Yes

Overview
General comments on the dataset

*There is only 1 reference period therefore does not need to filterable
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Additional contact details are available on the landing page and within the XLS spreadsheet 

Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

**Comment by mikeAdamss** [comment] 2020-04-22 10:37
raised the one line only download with swirrl

**Comment by JasonHowell** [comment] 2020-04-28 12:29
BA have reviewed but title is very long, could this be flipped?

**Comment by MartynBSpooner** [comment] 2020-04-29 10:59
Check PMD4 geographies are codes / string attributes.

**Comment by MartynBSpooner** [comment] 2020-04-29 11:01
Split out datasets to be re-merged into one cube - Leigh re-merging.

**Comment by mikeAdamss** [comment] 2020-04-29 14:18
think this is ok but pmd3 is caching the old comments/description despite efforts to change. Should be ok once the cache has cleared but needs confirming, will check in morning 30/4/2020)

**Comment by mikeAdamss** [comment] 2020-04-30 10:22
@JasonHowell - this looks done to me (at least on the data changes side).

was 2 dataset:
International exports of services from the UK by NUTS area, Industry and destination
International exports of services from the UK by Joint Authority, Industry and destination

is now one called: `International exports of services from subnational areas of the UK`.

Unsure if that means the BA's need to give it another look, and Swirrl may also need to know (not sure but I'd imagine they'll may need to delete both the old ones, probably worth a heads up).

**Comment by JasonHowell** [comment] 2020-04-30 14:39
Thanks @mikeAdamss   Will raise with BA's & Swirrl.

**Comment by ajtucker** [comment] 2020-05-01 10:27
@RobThomlinson pointed out that:

> The Reference Period is set to "2016-03-31 P1Y" when the dataset is actually for the 2017 calendar year.

> It's a slightly convoluted link, but the ONS Subnational dataset is aligned with the HMRC "Regional trade in goods disaggregated by smaller geographical areas: 2017" https://www.gov.uk/government/statistics/regional-trade-in-goods-statistics-dis-aggregated-by-smaller-geographical-areas-2017

**Comment by ajtucker** [comment] 2020-05-01 10:31
We need to either change the values of the "Period" column to be "year/YYYY", or change the column to "Year" and make the values "YYYY".

Also, if this transform results in a single data cube, we should be putting everything into one observations.csv file with one metadata file and schema.

**Comment by JasonHowell** [comment] 2020-05-06 07:26
There are two(three) datasets showing up on PMDv4.   Understood it was merged back to one, hence why are the others still showing?

**Comment by mikeAdamss** [comment] 2020-05-06 09:33
git issue, have fixed. Can you delete the duplicates again when you get a chance @ajtucker

**Comment by JasonHowell** [comment] 2020-05-06 12:18
Raised Swirrl issue #52 to remove duplicates.

**Comment by JasonHowell** [comment] 2020-05-06 14:11
Needs to be refreshed on PMDv4 and then reviewed by BA's.

**Comment by JasonHowell** [comment] 2020-05-13 08:18
Available on PMDv4 as one dataset now.  Just a quick review required from BA's.

**Comment by JasonHowell** [comment] 2020-05-20 08:59
BA's confirmed in stand-up "Good to go".

**Comment by santhosh-thangavel** [comment] 2021-01-22 11:42
For the information of DMs.
Note the following do not have a NUTS code and was taken from the old code.
# cambridgeshire-and-peterborough',
# 'greater-manchester', 'liverpool-city-region', 'inner-london',
# 'outer-london', 'north-of-tyne', 'sheffield-city-region',
# 'tees-valley', 'west-of-england', 'cardiff-capital-region',
# 'swansea-bay', 'aberdeen-and-aberdeenshire',
# 'edinburgh-and-south-east-scotland', 'glasgow-city-region'

**Comment by santhosh-thangavel** [comment] 2021-01-22 11:46
For the information of DMs.
Following areas do not have NUTS codes and was taken from the old code.
# cambridgeshire-and-peterborough',
# 'greater-manchester', 'liverpool-city-region', 'inner-london',
# 'outer-london', 'north-of-tyne', 'sheffield-city-region',
# 'tees-valley', 'west-of-england', 'cardiff-capital-region',
# 'swansea-bay', 'aberdeen-and-aberdeenshire',
# 'edinburgh-and-south-east-scotland', 'glasgow-city-region'

**Comment by santhosh-thangavel** [comment] 2021-01-22 11:47
For the information of DMs.
Following areas do not have NUTS codes and was taken from the old code.
# cambridgeshire-and-peterborough',
# 'greater-manchester', 'liverpool-city-region', 'inner-london',
# 'outer-london', 'north-of-tyne', 'sheffield-city-region',
# 'tees-valley', 'west-of-england', 'cardiff-capital-region',
# 'swansea-bay', 'aberdeen-and-aberdeenshire',
# 'edinburgh-and-south-east-scotland', 'glasgow-city-region'

**Comment by santhosh-thangavel** [comment] 2021-01-22 11:54
For information of DMs
Following areas don't have NUTS codes and was taken from the old codes
' cambridgeshire-and-peterborough',  'greater-manchester', 'liverpool-city-region', 'inner-london', 'outer-london',
'north-of-tyne', 'sheffield-city-region, tees-valley, 'west-of-england', 'cardiff-capital-region', 'swansea-bay', 'aberdeen-and-aberdeenshire', 'edinburgh-and-south-east-scotland', 'glasgow-city-region'

**Comment by rossbowen** [comment] 2021-01-26 17:12
`csvlint`  returns `invalid metadata: malformed JSON` regarding the `-metadata.json` file. Python can read the `.json` fine and I used another tool to validate the JSON is legit. Not sure why this is failing with `csvlint`.

**Comment by rossbowen** [comment] 2021-01-27 11:29
`csvlint` failing due to duplicate columns.

This bit of the code is transforming into nuts codes. 

```python
df['Service Origin Geography'] = df['Service Origin Geography'].map(
    lambda x: {  
        'United Kingdom':'nuts1/all',
        'North East ':'nuts1/UKC',
        'North West':'nuts1/UKD',
        'Yorkshire and The Humber':'nuts1/UKE',
        'East Midlands':'nuts1/UKF',
        'West Midlands':'nuts1/UKG',
        'East of England':'nuts1/UKH',
        'London':'nuts1/UKI',
        'South East':'nuts1/UKJ',
        'South West':'nuts1/UKK',
        'Wales':'nuts1/UKL',
        'Scotland':'nuts1/UKM',
        'Northern Ireland':'nuts1/UKN'      
        }.get(x, x))
```

Problem is, tab `4b` also has a header called `West Midlands` which corresponds to a city region, not the NUTS1 geography.

To summarise - could this be changed so the above mapping does not apply to data items coming from sheet `4b`?

**Comment by santhosh-thangavel** [comment] 2021-02-01 18:40
Mapping "Service Origin Geography" outputs to nuts1, nuts2 and nuts3 codes are not applied to values from '4a' and '4b' but are pathified.

**Comment by LPerryman** [comment] 2021-02-05 10:55
Have published on PMD4, current problem with all measure types showing as URIs in, it appears all datasets

**Comment by robons** [comment] 2021-03-22 16:43
I've ensured that all of the codelists are correctly specified and fixed the NUTS/Statistical Geographies amalgamation ConceptScheme.

@Tracey-B this will shortly be ready for review at https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk-catalog-entry&filters-drawer=open

Might be best to leave this until tomorrow as PMD appears to be having some problems.

**Comment by Tracey-B** [comment] 2021-03-23 08:00
@robons  BA checks completed comments below:

- Filter not required for flow
- Is the measure type correct and consistant with other trade datasets?
- Do the comments at the bottom of each tab need to be included somewhere?

**Comment by robons** [comment] 2021-03-23 08:22
> @robons BA checks completed comments below:
> 
>     * Filter not required for flow
> 
I've included the codelist for flow as I believe it may be required for Swirrl's new search interface to work - however no one's shared any specifics about the system's requirements with me so I'm just guessing.  

>     * Is the measure type correct and consistant with other trade datasets?
I don't believe we have any consistency with other trade datasets. We don't have any enforcable standards for measure type. I believe this is the most appropriate measure. If you see any *measures* such as "GBP Millions", these are inappropriate as the *unit* should be "GBP Millions", the measure ought to be something like "monetary value" since that is the thing being measured.  

> 
>     * Do the comments at the bottom of each tab need to be included somewhere?

I will take a look at this.

**Comment by robons** [comment] 2021-03-23 09:46
@Tracey-B 

I have updated the dataset so that dataset comment shows up correctly.

Following our other discussion, I've also stopped the values of suppressed values from showing up (incorrectly) as '0'. 

https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk-catalog-entry&order-by-component=http%253A%252F%252Fgss-data.org.uk%252Fdata%252Fgss_data%252Ftrade%252Fons-international-exports-of-services-from-subnational-areas-of-the-uk%2523dimension%252Fperiod&order-direction=ASC

**Comment by JasonHowell** [comment] 2021-08-09 10:51
Been published to the Beta site and looks fine. Closing issue.

**Closed by JasonHowell** 2021-08-09 10:51 UTC

**Comment by parmae** [comment] 2021-09-17 13:10
International exports of services from subnational areas of the UK: - line 399 changed. To reflect the new change/and new publication. 
2018 - International exports of services from subnational areas of the UK   
https://www.ons.gov.uk/businessindustryandtrade/internationaltrade/articles/internationaltradeinservicesbysubnationalareasoftheuk/2018
