### ISSUE TITLE
ONS-balance-of-payments

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#1] opened 2020-03-13 09:55 UTC

**Comment by VTula2000** [comment] 2020-03-13 17:01
Decision pending on to use time series data or Quarter release data
Previously worked on this url data https://www.ons.gov.uk/economy/nationalaccounts/balanceofpayments/datasets/balanceofpaymentsstatisticalbulletintables
Time series data(Available in info json)
https://www.ons.gov.uk/economy/nationalaccounts/balanceofpayments/datasets/balanceofpayments/current

**Comment by ajtucker** [comment] 2020-03-14 15:45
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-Total-trade/9/)

Blocks #6

**Comment by ajtucker** [comment] 2020-03-24 16:24
Jenkins job result: FAILURE
Stage: Validate CSV
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-Total-trade/10/)

Blocks #6

**Comment by ajtucker** [comment] 2020-03-25 17:18
Jenkins job result: FAILURE
Stage: Test draft dataset
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-Total-trade/11/)

Blocks #6

**Comment by ajtucker** [comment] 2020-03-25 22:40
Jenkins job result: FAILURE
Stage: Test draft dataset
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-Total-trade/12/)

Blocks #6

**Comment by ajtucker** [comment] 2020-03-26 10:39
Jenkins job result: FAILURE
Stage: Test draft dataset
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-Total-trade/13/)

Blocks #6

**Comment by ajtucker** [comment] 2020-03-26 10:56
Jenkins job result: FAILURE
Stage: Test draft dataset
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-Total-trade/14/)

Blocks #6

**Comment by ajtucker** [comment] 2020-03-26 11:38
Build was fixed!

**Comment by mikeAdamss** [comment] 2020-03-27 09:51
there is a pending question on this RE data source, for now just trying to get the existing pipeline for table f working again.

**Comment by JasonHowell** [comment] 2020-04-08 13:14
QA BA Feedback - David H

BA Quality Assurance High Level Checks 
Dataset: Quarterly Balance of Payments
Done by: David Hull
Date: 7-4-20
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes
Does transformed info seem to match the original?
Yes
Contents Modified Date
2019-01-24
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
No
Is there descriptive metadata on the PMD v3 landing page?
No access
Modified Date
27 Mar 2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
No
Does the structure look sensible?
Yes

Overview
General comments on the dataset

Latest version is available on the website landing page in XLS and CSV format.
Large single page spreadsheet.
Dataset seems to be well transformed from a data point of view.
Title on PMDv4 is “Balance of payments” but in airtable is “Quarterly Balance of payments” and in PMDv3 it’s “Quarterly Balance of payments: Trade in Services”.
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Metadata is available but there is no overview description in the “about” page.
Metadata is present in airtable.
Only a generic contact email addresses is noted in “about” but a more detailed specific contact is present in airtable and the landing page.
No link available to the original website landing page.
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

Overall column titles and items look sensible and do seem to match original data.
Only dimension with a filter is “Flow”.
Looks odd to me to have a “GBP Total” column of it’s own with “GBP total” the main (if not only) entry in the “measure type”.

Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

Overall, data seems consistent and looks sensible. Scaling looks correct but insufficient filtering and metadata could be more robust.

**Comment by ajtucker** [comment] 2020-04-08 17:10
Reopening - Jenkins was closing these when the pipeline succeeded.

**Comment by mikeAdamss** [comment] 2020-04-09 08:03
Moving to review.

This was an "update to the new world" of a very old pipeline. RE the data, it's table F only of the source spreadsheet. Not my choice, we just only did F originally (no idea if we want the rest).

Im unsure how much of the BA review comments apply as the pipeline was broken at the time, apply some common sense.

**Comment by RedWalters** [comment] 2020-04-14 13:18
- [x] **Does the dataset show up or is there an error?**

PMD4 : No

PMD3: http://gss-data.org.uk/dataset?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_bop

- [x] **Is it in the list of datasets from the main page?**
- [x] **Is there descriptive metadata on the search page?**

- [x] **Does transformed info match the original?**
Yes - Only simple transformations needed to be made due to small amount of data and small number of dimensions in a simple layout. However, only tab F is included in the pipeline. 
I can only find mention to someone else's question into why only F was originally taken but with no response. 

- [x] **Does the tidy-data download show all the data?**
Yes

- [x] **Note differences in column/row headers**
Unnamed column in the original data has been given the Title of CDID. No other changes to note.

- [x] **Are there multiple cubes? List titles of cubes**
N/A : One cube. (N.B. There were originally multiple cubes on this data set but was changed to only be tab F)

- [x] **What needs differentiating? Totals**
N/A

- [x] **Are there titles that need harmonizing? World/Worldwide**
N/A

- [x] **Does the structure look sensible?**
Yes. 
- [x] **Does the hierarchy work?**
Yes. 
- [x] **What needs further investigation or context?**
Explanation as to why only one tab is used. It might just be a case that only this tab is relevant to trade but if this is the case it needs to be noted for future reference. 


- [x] **Any duplications?**
No.
- [x] **List any detailed metadata/methodology to add retrospectively**
N/A

- [x] **Short metadata added**
N/A

**Comments:**

Small, simple transform and dataset. Only confusion is down to why only one of the tabs is used but it hopefully an easy explanation. 
If this is confirmed then this dataset can move to be checked over by BA.

**Comment by ajtucker** [comment] 2020-04-24 13:18
Due to the way we're managing the dataset uploads to PMD, if we change the graph URI of a dataset, e.g. because we need to turn a dataset into multiple cubes, then the pipeline won't know how to remove the old data when it tries to replace it with the new data.

I've added a proposal to use the `dcat:landingPage` to work out the graphs to delete, see GSS-Cogs/pmd-jenkins-pipeline#12.

In the meantime, I've manually removed the orphan/stale version of this dataset so we can get the right one into PMD4.

**Comment by JasonHowell** [comment] 2020-04-28 11:57
BA's have confirmed it is good to go in its current state.

**Comment by JasonHowell** [comment] 2020-05-18 11:09
Closing issue as now been deployed onto PMDv4.

**Comment by Shannon95** [comment] 2020-11-25 09:53
GitHub
https://github.com/GSS-Cogs/family-trade/tree/master/datasets/ONS_BoP
Jenkins
https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_BoP/

**Comment by Shannon95** [comment] 2020-12-04 13:11
Dataset has been updated with cube class and outputting required files fine, though I have a few thoughts/issues requiring clarity: 
-   RE the data it previously only brought in Table F of the source spreadsheet, it has now been updated to transform the rest of the sheets, do we require them? cannot seem to find a decision on this anywhere. 
- Table F seems to be the only table with Flow Directions so I have made the blank inputs "not-applicable", is that ok? 
- Now with all sheets being transformed BOP Services output options are much larger and therefore the Lookup does not reflect them all and might be better being handled by a code list, again not sure?

**Comment by Shannon95** [comment] 2021-02-18 09:00
Updates have been made bringing in the all of the tables as mentioned in the comment above. Due to this an extra dimension had to be brought in to avoid duplicates, called 'Account Type' this might not be reflective and might need to be changed by a DM. 

Removing the CDID issue label as I don't think we need them in here -- the dimensions are otherwise well defined. This needs checking with the publisher as we could leave them in as either attributes or more usefully as slice IDs.

The comments made above on 4th December still apply and need a DM to look and clarify, please.

**Comment by mikeAdamss** [comment] 2021-02-22 16:01
this got flagged when we were having issues with the refactored databaker. It's a transform code error rather than tooling.

**if we come back to this** then this line https://github.com/GSS-Cogs/family-trade/blob/5038711672b4cf6c46a7dec8d52ef2973bacef92/datasets/ONS_BoP/main.py#L81 needs to have `assert_one()` on the end, otherwise it'll do cooky things when it turns out that cell B1 actually _is_ blank (as one of our selection will actually be empty).

**Comment by rossbowen** [comment] 2021-04-09 08:57
Failing because CDIDs included in this dataset seem to have been lost from the CDIDs codelist.

**Comment by canwaf** [comment] 2021-04-12 09:00
Hey @rossbowen, I've generated and updated the codelist, but it appears to be failing on the SPARQL codelist check where `-MU7M != -MU7M`. So I'm stuck. Adding blocked. I think a data manager needs to figure out whether the negative CDID codes are being interpreted by SPARQL wrong.

**Comment by canwaf** [comment] 2021-04-12 09:04
For reference I checked this using the clipboard and python, and utf vs raw conversion and I think* this _isn't_ a encoding on the data side.
![image](https://user-images.githubusercontent.com/10587474/114369646-808b6f80-9b76-11eb-8a53-53ff05b85f8d.png)

**Comment by Shannon95** [comment] 2021-04-13 16:14
Had a quick look at this issue - failing to pick up the CDID codes as there appeared to be a leading space in the output. e.g. " -MU7M" 
removed space and passing SPARQL code list check now. Avilable for review here: https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-balance-of-payments-catalog-entry&apply-filters=true

**Comment by JasonHowell** [comment] 2021-08-06 10:50
This has been fixed and all passing on the master branch.  However it is failing on the Beta branch which is covered under #201.  

Closing this issue.

**Closed** 2021-08-06 10:51 UTC
