### ISSUE TITLE
ONS-pink-book-trade-in-services

### ISSUE THREAD

**Issue by MartynBSpooner** [GSS-Cogs/family-trade#34] opened 2020-03-18 17:32 UTC

**Comment by VTula2000** [comment] 2020-03-31 14:01
3.1 Data tab removed due to duplication of observations
Need clean some code, parts of notebooks are hard coded.

**Comment by VTula2000** [comment] 2020-04-06 12:25
'CWVK', 'CWVL' codes don't have BPM6 digital code 
https://drive.google.com/uc?export=download&id=1uNwmZHgq7ERqD5wcND4W2sGHXRJyP2CR

**Comment by VTula2000** [comment] 2020-04-06 14:19
- [ ] Does the dataset show up or is there an error?
- [ ]  Is it in the list of datasets from the main page?
- [ ]  Is there descriptive metadata on the search page?
- [ ]  Does transformed info match the original?
- [ ]  Does the tidydata download show all the data?
- [ ]  Note differences in column/row headers
- [ ]  Are there multiple cubes? List titles of cubes
- [ ]  What needs differentiating? Totals
- [ ]  Are there titles that need harmonising? World/Worldwide
- [ ]  Does the structure look sensible?
- [ ]  Does the hierarchy work?
- [ ]  What needs further investigation or context?
- [ ]  Any duplications?
- [ ]  List any detailed metadata/methodology to add retrospectively
- [ ]  Short metadata added

**Comment by JasonHowell** [comment] 2020-04-08 12:51
BA QA Feedback Tracey B

BA Quality Assurance High Level Checks 
Dataset: 03 Trade in services, The Pink Book
Completed by: Tracey Burgess 
Date: 06/04/2020
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
No*
Does transformed info seem to match the original?
Yes
Contents Modified Date
26/06/2018
PMD V3
Is the dataset listed  in PMD V3?
Yes**
Does the dataset open?
Yes both open 
Is there descriptive metadata on the PMD v3 landing page?
Yes for latest version 
Modified Date
31/03/2020
General
Is the dataset title meaningful?
Yes**
Do the filters work & look sensible?
No***
Does the structure look sensible?
Yes

Overview
General comments on the dataset

**There are 2 versions of this dataset in PMD V3:
ONS Pink Book Chapter 3 - Modified 26/06/2018
03 Trade in services, The Pink Book - Modified 31/03/2020

The latest version was published 31 October 2019 and modified 31/03/2020 in PMD V3, the version in PMD V4 Staging is out of date.




Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

*The following description is available on the landing page:
Detailed annual statistics on trade in services including transport, travel, insurance and pensions, financial, telecommunication and computer, cultural and recreational, and government.

The contents issued date on PMD4 staging is 31/10/2017 however on the landing page the current version was published 31/10/2019!

Better contact details are available on the landing page and Airtable:
Richard McCrae
bop@ons.gov.uk
+44 (0)1633 456106

Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

** the title of the dataset on PMDv4 staging makes sense although it does not match what is on Airtable or the landing page.

***PMD V4 Staging - Filters can only be applied to Flow, Measure type can be removed from the list of dimensions that can have filters applied as this is always GBP Total, also consider if Measure type and unit of measure are required as separate items within the dataset?
CDID needs to be added to the list of dimensions that can be filtered.

**Comment by ajtucker** [comment] 2020-04-08 17:05
Reopening as it's still to be fixed.

**Comment by VTula2000** [comment] 2020-04-14 09:13
- [ ] 'CWVK', 'CWVL' codes don't have BPM6 digital code
https://drive.google.com/uc?export=download&id=1uNwmZHgq7ERqD5wcND4W2sGHXRJyP2CR
- [ ] FJOW,FJQO and FJSI codes need to be updated in PMD so Jenkin get updated from Ref_CDID

**Comment by JasonHowell** [comment] 2020-04-28 11:43
BA's have confirmed it good to go in it's current state.

**Comment by JasonHowell** [comment] 2020-05-18 11:08
Closing issue as now been deployed onto PMDv4.

**Comment by ajtucker** [comment] 2021-02-13 17:04
Removing the CDID issue label as I don't think we need them in here -- the dimensions are otherwise well defined. This needs checking with the publisher as we could leave them in as either attributes or more usefully as slice IDs.

The geography dimension is actually a constant and not given explicitly in the data. It was originally set by us as UK as the dataset is specific to the UK. This should more readily be the "reference geography" for the dataset, although the cube spec would "[normalize](https://www.w3.org/TR/vocab-data-cube/#normalize)" it to apply to each observation. I tend to think that the spatio/temporal context of a dataset is more usefully given by the `dcat:spatio/temporal` properties on the `dcat:Dataset`, rather than made explicit as a constant dimension on every observation in the `qb:DataSet`.

I resurrected the `pinkbook-services.csv` from the `ref_trade` as I'm not sure where they've gone. There are some issues with the hierarchy as noted in the [latest test failures](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_PinkBook/lastCompletedBuild/testReport/(root)/pmd4_concept-schemes_SELECT_BroaderObjectsMustBeAConcept/Broader_Objects_Must_Be_A_Concept/).

**Comment by robons** [comment] 2021-02-22 09:06
Build problems, throwing back at Data Engineers.

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/usr/local/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 119, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 369, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/usr/local/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/local/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

tabs = [x for x in scraper.distribution(latest=True).as_databaker() if x.name in sheetname]
for tab in tabs:
    
    columns=["Geography", "Period", "CDID", "Pink Book Services", "Flow Directions", "Value", "Marker"]
    trace.start(tab.name, tab, columns, scraper.distributions[0].downloadURL)
    
    anchor = tab.excel_ref('B3')
    
    cdid = anchor.shift(1,0).fill(DOWN).is_not_blank().is_not_whitespace()
    trace.CDID("Selected cdids from column B")
        
    flow = anchor.fill(DOWN).one_of(['Exports (Credits)', 'Imports (Debits)', 'Balances'])
    trace.Flow_Directions("Set as one of 'Exports (Credits)', 'Imports (Debits)', 'Balances'")
    period = anchor.fill(RIGHT).is_not_blank().is_not_whitespace()            
    
    observations = period.fill(DOWN).is_not_blank().is_not_whitespace() 
    
    trace.Geography('Hard code geography to "K02000001"')
    geography = "K02000001"
    
    dimensions = [
                HDimConst('Geography', geography),
                HDim(period,'Period', DIRECTLY,ABOVE),
                HDim(cdid,'CDID', DIRECTLY,LEFT),
                HDim(flow, 'Flow Directions', CLOSEST, ABOVE)           

    ]
    c1 = ConversionSegment(tab, dimensions, observations)
    
    df = c1.topandas()
    df['Period'] = df['Period'].map(lambda cell: cell.replace('.0', '').strip())
    df['CDID'] = df['CDID'].str.strip()
    df['OBS'].replace('', np.nan, inplace=True)
    df['Flow Directions'] = df['Flow Directions'].map(
        lambda x: {
            'Exports (Credits)': 'Exports',
            'Imports (Debits)': 'Imports',
            'Balances': 'Balance'}.get(x, x))
    
    df.rename(index= str, columns={'OBS': 'Value'}, inplace=True)
    trace.store("pinkbook combined dataframe", df)

df = trace.combine_and_trace("pinkbook combined dataframe", "pinkbook combined dataframe")
df
------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-240e45b0fa93> in <module>
     29 
     30     df = c1.topandas()
---> 31     df['Period'] = df['Period'].map(lambda cell: cell.replace('.0', '').strip())
     32     df['CDID'] = df['CDID'].str.strip()
     33     df['OBS'].replace('', np.nan, inplace=True)

/usr/local/lib/python3.8/site-packages/pandas/core/series.py in map(self, arg, na_action)
   3826         dtype: object
   3827         """
-> 3828         new_values = super()._map_values(arg, na_action=na_action)
   3829         return self._constructor(new_values, index=self.index).__finalize__(self)
   3830 

/usr/local/lib/python3.8/site-packages/pandas/core/base.py in _map_values(self, mapper, na_action)
   1298 
   1299         # mapper is a function
-> 1300         new_values = map_f(values, mapper)
   1301 
   1302         return new_values

pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

<ipython-input-1-240e45b0fa93> in <lambda>(cell)
     29 
     30     df = c1.topandas()
---> 31     df['Period'] = df['Period'].map(lambda cell: cell.replace('.0', '').strip())
     32     df['CDID'] = df['CDID'].str.strip()
     33     df['OBS'].replace('', np.nan, inplace=True)

AttributeError: 'float' object has no attribute 'replace'
AttributeError: 'float' object has no attribute 'replace'
```

**Comment by mikeAdamss** [comment] 2021-02-22 13:38
we've rolled back the databaker change that caused the above (missing type casting). this is back to failing sparql tests.

**Comment by LPerryman** [comment] 2021-03-01 11:11
Dataset has been published to PMD4:
https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_pinkbook-catalog-entry

Have removed 2 CDIDs as they are not currently in the list (CWVK, CWVL'). Have spoken to BAs who have emailed the publishers to ask if they have the information to be added to the reference file.

The above mentioned reference file sits on goggle drive and is referenced in main.py, code segment below:

PBclassification_table_url = 'https://drive.google.com/uc?export=download&id=1uNwmZHgq7ERqD5wcND4W2sGHXRJyP2CR'
classifications_table = pd.read_excel(PBclassification_table_url, sheet_name = 0)
df = pd.merge(df, classifications_table, how = 'left', left_on = 'CDID', right_on = 'cdid')
df = df.rename(columns={'BPM6':'Pink Book Services'})

can we move this file to ref_cdid and reference it from there please?
will also need to be updated with new info if publishers get back to BAs about new CDIDs

**Comment by mikeAdamss** [comment] 2021-03-02 09:29
updated as per the above comments on getting the classifications table into `ref_CDID`, moving it over.

**Comment by LPerryman** [comment] 2021-03-02 09:56
Thanks Mike

**Comment by JasonHowell** [comment] 2021-08-09 11:01
Closing as per comments above and it's fine on the Beta site.

**Closed by JasonHowell** 2021-08-09 11:01 UTC
Labels: BA Review
