### ISSUE TITLE
ONS_MRETS

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#5] opened 2020-03-13 09:55 UTC

**Comment by ajtucker** [comment] 2020-03-14 15:35
Jenkins job result: FAILURE
Stage: Transform
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC_OTS_CN8/79/)

Blocks #14

**Comment by ajtucker** [comment] 2020-03-14 15:41
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-International-Trade-in-Services/78/)

Blocks #4

**Comment by ajtucker** [comment] 2020-03-16 13:29
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-REUK-Service/48/)

Blocks #25

**Comment by ajtucker** [comment] 2020-03-19 14:26
Build was fixed!

**Comment by ajtucker** [comment] 2020-04-08 17:06
Reopening - Jenkins was closing these when the pipeline succeeded.

**Comment by mikeAdamss** [comment] 2020-04-23 13:50
There are two other associated datasets that need doing from this source, see task: https://github.com/GSS-Cogs/family-trade/issues/63

**Comment by VTula2000** [comment] 2020-04-23 16:34
DE's Comments
- [ ] Issues on PMDv4
- https://github.com/Swirrl/ons-data-export/issues/31

- [ ] All trade products data available in final data, foreign exchange and currency time data excluded 

- [ ] Data consistent, labels segregated as according to codes in various dimensions

**Comment by VTula2000** [comment] 2020-04-23 16:36
@JasonHowell Further BA to comments

**Comment by mikeAdamss** [comment] 2020-04-23 16:54
to clarify the above linked issue: there are currently duplicate entries for this dataset on pmd3 (we need to fix that), but one of those **is** the actual final version that needs a review.

you should be able to review the finished article while we clean up the left overs.

the one you actually want is: http://gss-data.org.uk/dataset?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_mrets

**Comment by JasonHowell** [comment] 2020-04-28 12:16
BA have confirmed good to go. One observation the landing page has it as 9/4, on PMD it is showing as 8/4.

**Comment by JasonHowell** [comment] 2020-05-18 10:51
Closing issue as now been deployed onto PMDv4.

**Comment by canwaf** [comment] 2020-12-07 15:27
CDID issues abound; waiting on @RobThomlinson to investigate the progress on DAP-sourced code lists before proceeding. Changes sashed and progress blocked until then. Status is blocked.

**Comment by canwaf** [comment] 2021-02-01 15:31
Minimal refactoring of the code; though I am not certain whether the output's MRETS Product values are descriptive enough; or whether it contains the data necessary for the code lists to provide the "richer text" side of things as seen on the trade alpha PMD site.

For the DM, please let me know whether this is the level of descriptiveness you want.

**Comment by mikeAdamss** [comment] 2021-02-22 16:16
hey @AndrewtGSScogs , this was on my big list of things broken by the deployment but turns out its not connected. Looks to me it's just good old fashioned broke. 

Not sure if you wanted to poke into it (feel free if you do :smile:) but it's arguably a DE task, so throw it back over if you want to and someone will pick it up.

**Comment by AndrewtGSScogs** [comment] 2021-02-23 07:52
Morning, @mikeAdamss Ahhh right oh I was mainly looking at the RDF output of it yesterday! Happy to have a poke around ive been hunting for a DE challenge to help my understanding of the whole pipeline. So if its ok I am happy to have a go at it as its not connected so i wont break anything! haha.

**Comment by mikeAdamss** [comment] 2021-03-01 09:34
no worries @AndrewtGSScogs , as I recall this one is right pita 😄 . I'll pick it up, can't really shadow as I've no idea how to do it (will need to hack at it a bit) but when I've straightened it out we can have a call and I'll walk you through it.

**Comment by mikeAdamss** [comment] 2021-03-01 11:57
this was a bit mad, the transform was fine but the pipeline was using an outdated version of databaker-docker/gssutils and trying to transform an old source (v11) rather than what it was intended for (v78). Have added a card to look at whats going on with that.

its running properly now (with the same transform code it had all along) and getting to sparql tests so moving it over.

**Comment by canwaf** [comment] 2021-03-01 13:29
I can absolutely agree, @mikeAdamss, we really don't want to change this pipeline if we can help it. It may be a legacy debt situation, but I hope the pipeline lives as long as the dataset, and both sunset on the same day.

**Comment by LPerryman** [comment] 2021-03-08 11:44
Need to create a product codelist as these are bespoke ones. Have asked Mike to leave in the product string so this can be done.

**Comment by mikeAdamss** [comment] 2021-03-08 12:39
Have updated output to include a `product_label` column with the product strings in it. If I'm understanding that should suffice for sorting out the codelists (if not, kick it back, no worries).

**Comment by LPerryman** [comment] 2021-03-12 10:16
Have only published CVM data for now. CP data will need Trade Area mapped to codes

**Comment by rossbowen** [comment] 2021-04-13 18:41
Lacking codelists - filters not working.

**Comment by Shannon95** [comment] 2021-04-19 11:45
Filters now working ( except for period as dataset is too large to generate codelist on fly) 
available on PMD4 here  for reference: https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_mrets-catalog-entry&apply-filters=true

**Comment by Shannon95** [comment] 2021-04-23 11:17
Dataset's now displaying as expected and ready for review: 
[UK trade time series - Chained Value Measures](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_mrets%2Fuk-trade-time-series-chained-value-measures-catalog-entry)
[UK trade time series - Current Prices](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_mrets%2Fuk-trade-time-series-current-prices-catalog-entry)

**Closed** 2021-08-06 10:53 UTC
