### ISSUE TITLE
ONS-Quarterly-country-and-regional-GDP

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#85] opened 2020-10-21 17:10 UTC
https://github.com/GSS-Cogs/family-trade/tree/master/datasets/ONS-Quarterly-country-and-regional-GDP

**Comment by CharlesRendle** [comment] 2020-10-28 14:15
Was unsure which values to assign as units as each tab contains multiple measures and unit is not immediately obvious.

Each dataframe still contains multiple measures which I expect to break up in stage 2.

tab_title still contains superscripts.

**Comment by rossbowen** [comment] 2021-01-26 09:42
Failing Jenkins tests atm - looks like a lot of the data is duplicated in the `.csv` output, so `csvlint` is throwing exceptions.

https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-Quarterly-country-and-regional-GDP/1/console

**Comment by robons** [comment] 2021-02-09 15:30
I've made some updates to better specify the measures and units as well as setting some codelists. We need a few more DE changes which need to happen to get it inline with what we're doing elsewhere.

Note that this is a multi-measure, multi-unit dataset with a (now) blended codelist referencing existing Concept URIs.

* Map region column to the following codes:
  * http://statistics.data.gov.uk/id/statistical-geography/E92000001 - England
  * http://data.europa.eu/nuts/code/UKF - EAST MIDLANDS (ENGLAND)
  * http://data.europa.eu/nuts/code/UKG - WEST MIDLANDS (ENGLAND)
  * http://data.europa.eu/nuts/code/UKE - YORKSHIRE AND THE HUMBER
  * http://data.europa.eu/nuts/code/UKC - NORTH EAST (ENGLAND)
  * http://data.europa.eu/nuts/code/UKD - NORTH WEST (ENGLAND)
  * http://data.europa.eu/nuts/code/UKZ - EXTRA-REGIO NUTS 1
  * http://data.europa.eu/nuts/code/UKK - SOUTH WEST (ENGLAND)
  * http://data.europa.eu/nuts/code/UKL - WALES
  * http://data.europa.eu/nuts/code/UKJ - SOUTH EAST (ENGLAND)
  * http://data.europa.eu/nuts/code/UKH - EAST OF ENGLAND
  * http://data.europa.eu/nuts/code/UKI - LONDON
* Delete `Unit` column.
* Rename `Measure Type` column to `Unit`.
  * Rename all `percentage-change` values to `percentage`.
  * Leave `indices` as they are.
* Rename `Change Type` column to `Measure Type`. The following measures should be in place:   
  * Rename all `not-applicable` values to `gdp-from-gva`
  * Rename all `quarter-on-previous-quarter` values to `q-on-q-delta-gdp-from-gva`
  * Rename all `quarter-on-same-quarter-a-year-ago` values to `q-on-last-year-q-delta-gdp-from-gva`
  * Rename all `year-on-year` values to `y-on-y-delta-gdp-from-gva`


@CharlesRendle or @Shannon95 I don't know whether one of you wants to pick this up?

**Comment by rossbowen** [comment] 2021-02-19 10:53
@Tracey-B 
Ready for review:
https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-quarterly-country-and-regional-gdp-catalog-entry&filters-drawer=open&show-uris=true

**Comment by robons** [comment] 2021-02-19 10:59
@rossbowen - There's a bit of an unexpected behaviour here. It's partitioning observations by the measure. No observation has all three values (which some should do).

**Comment by rossbowen** [comment] 2021-02-19 11:44
@robons you're right - though I believe this is the PMD4 platform making a decision on how to display the data rather than any particular issued with the underlying RDF - if we think this is a problem in the UX space (or that it should be squashed) we can raise an issue.

**Comment by robons** [comment] 2021-02-19 11:48
I think there is a UX issue here, but we're also coining unique URIs depending on the observation's measure type - which we have to do to meet the qb specification. So I'm not sure how PMD would know which observations should be grouped together. I guess they could group observations by dimension (excluding the one which defines the measure)?

But perhaps we need to start defining slices of data grouping these observations together and telling PMD that this is how they should be displayed? I guess this will affect all multi-measure datasets.

Any thoughts @ajtucker?

**Comment by rossbowen** [comment] 2021-02-19 12:01
Something like this?

```turtle
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?obs ?measure_type_label ?value
WHERE { 
  ?obs qb:dataSet <http://gss-data.org.uk/data/gss_data/trade/ons-quarterly-country-and-regional-gdp#dataset> .
  ?obs qb:measureType ?measure_type .
  ?measure_type rdfs:label ?measure_type_label .
  ?obs ?measure ?value .
  ?measure a qb:MeasureProperty .
}
```

**Comment by Tracey-B** [comment] 2021-02-24 09:37
@rossbowen BA check complete with the following comments:

- There is no Tech spec for this dataset.
- Unable to filter by measure type or period.
- Should it be possible to filter by unit of measure ans this is a multi-unit dataset (percentage and indices)? 
- All areas are displayed as words apart from England which s displayed as code E92000001.

**Comment by Robsteranium** [comment] 2021-05-05 08:17
I wonder if we could find ONS Geography codes instead of coining new URIs for the geographies. Indeed I'd suggest we ask ONS Geography to coin codes for any that are missing.

**Comment by Robsteranium** [comment] 2021-05-05 09:01
In case you've not seen it, the spec offers two ways of [handling multiple measures](https://www.w3.org/TR/vocab-data-cube/#dsd-mm), multi-measure observations vs the measure (type) dimension.

We've ended up settling on the measures dimension approach because it makes it possible to mix attribute properties. With multi-measures, all the measures are attached to the same observation so the attribute properties need to be shared. It's not so much [a problem with how we show the unit](https://github.com/GSS-Cogs/family-trade/issues/85#issuecomment-782001876) (or the observation-status marker) as with how we're able to model it.

I agree the tidy view does have some UX drawbacks (but I think the simplicity is worth it). We explored an alternate tidyish UI that rolled-up measures as part of the alpha. This leads to a lot of other problems. There's a [thread about display options on cogs-issues](https://github.com/Swirrl/cogs-issues/issues/207) to discuss this.

There are further problems with this cube however, so it's not just a UX problem in this case...

> I'm not sure how PMD would know which observations should be grouped together

In theory all the `?cube qb:structure/qb:dimension ?dimension` minus `qb:measureType` should identify an observation with each of it's measures. This is what distinguishes dimensions from attributes - the latter should serve to locate observations uniquely within the cube.

That condition appears to be violated in this cube. [This query suggests that there are multiple observations distinguished only be attribute](https://beta.gss-data.org.uk/tools/sparql?query=PREFIX%20qb%3A%20%3Chttp%3A%2F%2Fpurl.org%2Flinked-data%2Fcube%23%3E%0APREFIX%20sdmxa%3A%20%3Chttp%3A%2F%2Fpurl.org%2Flinked-data%2Fsdmx%2F2009%2Fattribute%23%3E%0A%0ASELECT%20%3Fmeasure%20%3Funit%20%3Fstatus%20(COUNT(*)%20as%20%3Fcount)%0AWHERE%20%7B%0A%20%20%3Fobs%20qb%3AdataSet%20%3Chttp%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-regional-gross-domestic-product-city-regions%23dataset%3E%3B%0A%20%20%20%20qb%3AmeasureType%20%3Fmeasure%3B%0A%20%20%20%20sdmxa%3AunitMeasure%20%3Funit%3B%0A%20%20%20%20.%0A%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fobs%20sdmxa%3AobsStatus%20%3Fstatus%3B%0A%20%20%7D%0A%7D%0AGROUP%20BY%20%3Fmeasure%20%3Funit%20%3Fstatus%0AORDER%20BY%20%3Fmeasure%20%3Funit%20%3Fstatus). Were it not to time-out, I would expect IC-12 to fail.

We could resolve this by making a unit dimension although that would lead to sparseness (worsening the UX).

Alternatively we could extend the cvm measure to have sub-measures (rate, index, value) - potentially keeping just one of the orders of magnitude for value.

Another option would be to make rate and index attributes themselves (this seems reasonable given the CVM methodology).

We could also partition the cube into subsets with coherent measures (shifting this to a discoverability/ cataloguing problem).

A further option would be to have the measure property point at resource instead of a literal. This resource could itself contain arbitrary values and attributes. This would mean a clean data model, a foundation for cell annotation for a cleaner UI, but wouldn't solve the problem for tabular downloads (we'd need to denormalise it again, and now the csv wouldn't match the UI).

**Comment by ajtucker** [comment] 2021-05-13 09:18
Some [recent fixes to CSV2RDF](https://github.com/Swirrl/csv2rdf/commit/8f36a4d6dc5f2e35ee6f23b8845c1001dd7af81b) mean that we need to update our CSV-W JSON files that use URI templates like `{uri}` to use `{+uri}` instead.

- [ ] [`"valueUrl": "{parent_uri}"`](https://github.com/GSS-Cogs/family-trade/blob/master/datasets/ONS-Quarterly-country-and-regional-GDP/codelists/reference-area.csv-metadata.json#L21) should be `{+parent_uri}`.
- [ ] [`"aboutUrl": "{uri}"`](https://github.com/GSS-Cogs/family-trade/blob/master/datasets/ONS-Quarterly-country-and-regional-GDP/codelists/reference-area.csv-metadata.json#L42) should be `{+uri}`.
- [ ] [`"value": "{reference_area}"`](https://github.com/GSS-Cogs/family-trade/blob/master/datasets/ONS-Quarterly-country-and-regional-GDP/info.json#L27) should be `{+reference_area}`.

**Comment by JasonHowell** [comment] 2021-08-10 11:43
Closing issue as the ones open will be dealt with separately.

This has been published to the Beta env.

**Closed by JasonHowell** 2021-08-10 11:43 UTC
Labels: BA Review
