### ISSUE TITLE
HMRC-OVERSEAS-TRADE-STATISTICS

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#10] opened 2020-03-13 09:55 UTC

**Comment by JasonHowell** [comment] 2020-05-18 12:44
@ajtucker Is this part of Trade?   If not, should this be closed?

**Comment by ajtucker** [comment] 2020-05-19 06:22
This one is listed in Airtable, but I'm not sure whether it is subsumed by the other HMRC OTS datasets or needs to be kept as a separate placeholder. @RobThomlinson ?

**Comment by JasonHowell** [comment] 2020-05-20 08:20
@ajtucker   Rob's comments from Slack "I Have Overseas Trade Statistics (CN8)- HMRC (published on PMD) and OVERSEAS TRADE STATISTICS - HMRC on airtable, they are the same thing.  I don't have anything anywhere listed as HMRC OTS, but OTS is a "normal" abbreviation for Overseas Trade Statistics, so best guess is that it is the same thing"

**Comment by JasonHowell** [comment] 2020-05-28 09:55
This is a duplicate of Overseas Trade Statistics (CN8) #14, hence closing issue.

**Closed by JasonHowell** 2020-05-28 09:55 UTC
Labels: BA Done
