### ISSUE TITLE
ONS-UK-trade-in-goods-by-industry-country-and-commodity

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#3] opened 2020-03-13 09:55 UTC
https://github.com/GSS-Cogs/family-trade/tree/master/datasets/ONS-UK-trade-in-goods-by-industry-country-and-commodity

**Comment by VTula2000** [comment] 2020-03-23 10:14
Tidy data Jupyter file couldn't finishes run, delays in data baker way to convert dimensions and observations to table.
Need a re look

**Comment by ajtucker** [comment] 2020-03-23 16:22
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_BoP_individual_countries/41/)

Blocks #33

**Comment by ajtucker** [comment] 2020-03-26 18:24
Jenkins job result: FAILURE
Stage: Validate CSV
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_BoP_individual_countries/42/)

Blocks #33

**Comment by ajtucker** [comment] 2020-03-27 13:06
Build was fixed!

**Comment by mikeAdamss** [comment] 2020-03-31 08:45
There's been something of a mix up of cards. This one is a jenkins job thats been repurposed as (the wrong) pipline.

Was labelled `ONS trade in goods by industry country and commodity`.

Have renaed it to `ONS BOP countries` to match the jenkins job (looks like this the pipeline the associated work was done on).

**Comment by JasonHowell** [comment] 2020-04-08 13:20
BA QA Feedback  David H

BA Quality Assurance High Level Checks 
Dataset: Trade in goods: country-by-commodity exports
Completed by: Tracey Burgess
Date: 06/04/2020
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes*
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes
Does transformed info seem to match the original?
Yes*
Contents Modified Date
10/01/2019
PMD V3
Is the dataset listed  in PMD V3?
Yes 
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
10/01/2019
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
No**
Does the structure look sensible?
Yes

Overview
General comments on the dataset

*the data set is an amalgamation of 2 separate data sets (imports and exports) Title in PMD is Trade in goods: country-by-commodity imports and  exports.
 
This is not the most recent publication, both publications were published 11/03/2020, next release is due 09/04/2020.
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Better contact details are available on the landing page and XLS spreadsheet 
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

**Not able to filter Product or Reference period 
**Do not need to filter by Measure type or Seasonal Adjustment 
**Is unit of measure and measure type required?
Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

**Comment by mikeAdamss** [comment] 2020-04-15 11:51
- [] Does the dataset show up or is there an error?
- [] Is it in the list of datasets from the main page? 
- [] Is there descriptive metadata on the search page? 
- [] Does transformed info match the original? 
- [] Does the tidydata download show all the data? 
- [] Note differences in column/row headers
- [] Are there multiple cubes? List titles of cubes
- [] What needs differentiating? Totals
- [] Are there titles that need harmonising? World/Worldwide 
- [] Does the structure look sensible?
- [] Does the hierarchy work? 
- [] What needs further investigation or context? 
- [] Any duplications? 
- [] List any detailed metadata/methodology to add retrospectively
- [] Short metadata added

**Comment by mikeAdamss** [comment] 2020-04-15 12:44
have messaged swirrl in cogs_techincal RE missing Product filter on pmd4

**Comment by mikeAdamss** [comment] 2020-04-15 13:19
reference period filter is fixed so barring the product filter fix (which is out of our hands but being worked on) I think this is done.

**Comment by JasonHowell** [comment] 2020-04-17 06:53
Sorry pasted the wrong BA Feedback:

BA Quality Assurance High Level Checks 
Dataset: UK trade in goods by industry, country and commodity, exports
Done by: David Hull
Date: 7-4-20
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes
Does transformed info seem to match the original?
Yes
Contents Modified Date
2020-03-10
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
30 Mar 2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
Mostly
Does the structure look sensible?
Yes

Overview
General comments on the dataset

Latest release is present on the website landing page is 2008 to 2017, next release TBA.
Large single page XLSspreadsheet with simple structure and dimensions.
Dataset seems to be well transformed from a data point of view but not all dimensions have a filter on PMDv4.
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Metadata is present in the “about” page.
Metadata is present in airtable.
Only a generic contact email addresses is noted in “about” but a more detailed specific contact is present in XLS spreadsheet contents page.
No link available to the original website landing page.
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

Overall column titles and items look sensible and do seem to match original data.
No filter available on “Product”,”Reference Period” or “measure type”, though “measure type” seems to only consist of “GBP Total” - if so, of course this would negate the need for a filter. Looks odd to me to have a “GBP Total” column of it’s own with “GBP total” the main (if not only) entry in the “measure type”.
Is observation status a necessary column or might it be hidden?

Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

Overall, data seems consistent, to scale and looks sensible, with the exception of the above points.

**Comment by JasonHowell** [comment] 2020-04-17 06:55
@mikeAdamss Sorry I copied the wrong BA feedback in.  Could you look at the above and see if anything needs to be amended?  Thanks Jason.

**Comment by mikeAdamss** [comment] 2020-04-17 10:54
Checked by Dave. BA's to discuss on Monday 20/4/2020. Will close (or investigate any further comments if needd) after that.

**Comment by mikeAdamss** [comment] 2020-04-22 09:45
closing, issues raised via git repos (gssutils for ours, swirrls repo for pmd4 related).

**Comment by mikeAdamss** [comment] 2020-04-30 08:05
@JasonHowell - RE davids point `Looks odd to me to have a “GBP Total” column of its own with “GBP total” the main (if not only) entry in the “measure type”.`

Heard back from Swirrl on that, it's the intended behaviour of PMD4 that where the "Value" column consists of a measure then that measure is used as the column header (i.e this is intended behaviour not a mistake). 

Not saying its right (I'm on the fence) but if the BA's decide they don't like this approach, it'll need to be feedback to Swirrl about the pmd4 platform itself, as it's not specific to this dataset or under our control.

**Comment by JasonHowell** [comment] 2020-04-30 14:17
Reached out to David based on the above comment, to see if it can now go out for final review?

**Comment by JasonHowell** [comment] 2020-05-01 08:01
This was discussed on slack with Mike and BA's.  BA's happy for it to go forward. Updated label.

**Comment by JasonHowell** [comment] 2020-05-18 11:01
Closing issue as now been deployed onto PMDv4.

**Comment by Shannon95** [comment] 2020-12-18 09:46
- [x] Add Cubes() to transform (DE)

**Comment by Tracey-B** [comment] 2021-02-02 07:13
BA Comments:

This data set is an amalgamation of 2 separate data sets (imports and exports), no Tech Spec has been produced.  The dataset in PMD4 appears sensible subject to the following comments:  

- none of the filters are available 

- the Identifier  http://gss-data.org.uk/data/gss_data/-trade-/ons-uk-trade-in-goods-by-industry-country-and-commodity-catalog-entry link  in the about tab is returning a Server Error (500).

**Closed** 2021-08-09 10:40 UTC
Labels: Not on PMD4
