### ISSUE TITLE
ONS-foreign-direct-investment-involving-uk-companies

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#28] opened 2020-03-17 14:22 UTC
https://github.com/GSS-Cogs/family-trade/tree/master/datasets/ONS-FDI

**Comment by VTula2000** [comment] 2020-04-06 14:18
- [ ] Does the dataset show up or is there an error?
- [ ]  Is it in the list of datasets from the main page?
- [ ]  Is there descriptive metadata on the search page?
- [ ]  Does transformed info match the original?
- [ ]  Does the tidydata download show all the data?
- [ ]  Note differences in column/row headers
- [ ]  Are there multiple cubes? List titles of cubes
- [ ]  What needs differentiating? Totals
- [ ]  Are there titles that need harmonising? World/Worldwide
- [ ]  Does the structure look sensible?
- [ ]  Does the hierarchy work?
- [ ]  What needs further investigation or context?
- [ ]  Any duplications?
- [ ]  List any detailed metadata/methodology to add retrospectively
- [ ]  Short metadata added

**Comment by IeuanMan** [comment] 2020-04-08 13:15
@Tracey-B 

https://docs.google.com/document/d/1aEZOh0H2xcuu5xa-RzlDW1R0Gqoe7KFHoKPE5scoD5I/edit#heading=h.7783s8wimep8

BA Quality Assurance High Level Checks 
Dataset: Foreign direct investment involving UK companies: inwards 
Completed by: Tracey Burgess 
Date: 03/04/2020
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes
Does transformed info seem to match the original?
Yes*
Contents Modified Date
16/03/2020
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
26/03/2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
No**
Does the structure look sensible?
Yes

Overview
General comments on the dataset

** unable to filter on reference period 
** unable to filter measure  type this should be removed from the dataset dimensions the same as unit of measure & GBP Total


Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data
*the data set is an amalgamation of 2 separate data sets (inward and outward), it may be helpful to include this in the title or in the brief description on the landing page.

Correct published date present although this is named Contents Issued

Contact details are correct taken from the landing page (although the name Andrew Jowett, is displayed when clicking on the link the fdi@ons.gov.uk is displayed) the following details are contained within the XLS spreadsheet - Statistical contact: Andrew Jowett, Office for National Statistics, Telephone Number: +44 (0)1633 455357, need to consider if this is required or if this should be listed under contributor?

Contents Modified
2020-03-16T11:49:18.438Z  Appears PMDv3 is more recent than v4
Creator is this the correct term? - this links to a gov.uk page naming ONS?
There doesn't appear to be a link to the original data set that has been transformed, this may be because 2 different datasets were amalgamated?
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

Should Investment direction be Flow?
Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

**Comment by VTula2000** [comment] 2020-04-14 09:09
Data Marker dimension added to data, removed duplication

**Comment by JasonHowell** [comment] 2020-04-15 10:45
@VTula2000   Thanks for moving to Needs sign-off.  However, I cannot see what was done against the BA comments.  Please could you update?  If you look at JJ's & Shannon's one's in the sign-off as a template that would be great.   Thanks Jason

**Comment by VTula2000** [comment] 2020-04-15 16:57
Comments on BA review

- [ ] **PMDv4** not updated, latest data available from http://gss-data.org.uk/dataset?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-fdi
that reflecting an extra column in PMD3 , i.e `Data Marker`

- [ ] **Filtration errors**
** unable to filter on reference period
** unable to filter measure type this should be removed from the dataset dimensions the same as unit of measure & GBP Total

- There are various issues across dataset related to reference period, raised with Alex, soon get updates
- In PMDv4 has filter Measure type not in PMD3, that's error in PMD4?, need to check further
  because data set don't have multiple measure type, this data set has only one measure type( so no filter)
- [ ] **Metadata** Further need to be discussed with DM's, about content to display related to data merges and contributor information

- [ ] **Dimensions**
Do the column titles look sensible? Do the items look sensible? Does it match the original data?
Should Investment direction be Flow?

- Yes, Previous trello cards have decision logs related to dimensions titles, due to merging of two data sets inward and outward, and also various tabs in data set

-[ ] Observations
All observation reviewed looks okay

**Comment by JasonHowell** [comment] 2020-04-20 09:05
@VTula2000   Is the latest version available on PMDv4 as now is published?

**Comment by VTula2000** [comment] 2020-04-20 09:27
https://github.com/Swirrl/ons-data-export/issues/16

**Comment by JasonHowell** [comment] 2020-04-30 14:29
Latest version on PMDv4.  Now needs BA's to review.

**Comment by JasonHowell** [comment] 2020-05-06 14:13
BA's reviewed and good to go.

**Comment by JasonHowell** [comment] 2020-05-18 10:55
Closing issue as now been deployed onto PMDv4.

**Comment by ajtucker** [comment] 2021-02-14 18:46
There are two rows where no value has been given for the measure but there's also no marker:

```
inward,2013,BPM6,fdi/denmark,total-net-fdi-international-investment-position-in-the-uk-at-end-period,mining-quarrying,,
outward,2013,BPM6,fdi/europe,total-net-fdi-abroad,electricity-gas-water-and-waste,,
```

There needs to be either a value or a marker.

**Comment by mikeAdamss** [comment] 2021-02-18 13:31
this seems to be linked to the ONS scraper pulling wrong versions of the data, on the actual newest version it works fine. This should get fixed when this gets merged and released: https://github.com/GSS-Cogs/gss-utils/pull/185

**Comment by mikeAdamss** [comment] 2021-02-22 12:46
fixed by latest gssutils build. moving it over.

**Comment by rossbowen** [comment] 2021-03-03 08:22
Codelists have become out of sync with what is being output by the transform. The transform results in areas such as `central` being produced which I assume are meant to be `central-europe` or something along those lines.

**Comment by mikeAdamss** [comment] 2021-03-03 15:21
fixed the FDI Area issues, was a bit of a pain as the structure has changed so we were ending up with two slightly different labels for the same thing, eg `central-european` as well as `central-european-countries` depending on where it was sourced. Added a lookup to force consistency.

there's now two test separate failures related to codelists so moving it back over (happy to do if someone can comment on what the cause is).

**Comment by JasonHowell** [comment] 2021-08-09 10:55
The Theme on datasets is an URI and not a friendly name.  This just needs tweaking.

**Comment by Shannon95** [comment] 2022-04-27 12:46
closing off due to dataset being uplifted and refreshed.

**Closed by Shannon95** 2022-04-27 12:46 UTC
Labels: BA Review
