### ISSUE TITLE
ONS-UK-SA-Trade-in-goods

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#2] opened 2020-03-13 09:55 UTC

**Comment by ajtucker** [comment] 2020-03-16 10:29
Feedback from DIT:

> some of the geography labels don't match the original spreadsheet. Most notably "Total EU 28" is labelled as "ACP" in the GSS data and "Total Extra EU 28 (Rest of World)" is labelled as "Extra EU-25 - world less EU-25 countries"

- [ ] Fix geographies

**Comment by ajtucker** [comment] 2020-03-16 10:56
- [ ] Output metadata to `observations.csv-metadata.trig`

**Comment by IeuanMan** [comment] 2020-04-08 13:26
@david-hull 

https://docs.google.com/document/d/1YutxOExPSV5w4tSZ1jH20SXzOZLwQQ9GqUj-XWzSW7c/edit

BA Quality Assurance High Level Checks 
Dataset: Trade in goods: all countries, seasonally adjusted
Done by: David Hull
Date: 6-4-20
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes
Does transformed info seem to match the original?
Yes
Contents Modified Date
2020-03-10
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
26 Mar 2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
Mostly
Does the structure look sensible?
Yes

Overview
General comments on the dataset

Website landing page only has the current release.
Very large XLS spreadsheet but with simple structure and dimensions.
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Metadata is present in the “about” page.
No link available to the original website landing page.
Only a generic email address in contact detail, whereas a specific contact name is present in airtable.
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

No filter available for “Reference Period”.
Looks odd to me to have a “GBP Total” column of it’s own with “GBP total” the main (if not only) entry in the “measure type”.
Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

Overall, data seems consistent, to scale and looks sensible.

**Comment by ajtucker** [comment] 2020-04-08 17:28
VCard style contact details need to be added to gss-utils GSS-Cogs/gss-utils#44.

**Comment by Shannon95** [comment] 2020-04-15 11:23
- [ ] Does the dataset show up or is there an error?
- [ ] Is it in the list of datasets from the main page?
- [ ] Is there descriptive metadata on the search page?
- [ ] Does transformed info match the original?
- [ ] Does the tidydata download show all the data?
- [ ] Note differences in column/row headers
- [ ] Are there multiple cubes? List titles of cubes
- [ ] What needs differentiating? Totals
- [ ] Are there titles that need harmonising? World/Worldwide
- [ ] Does the structure look sensible?
- [ ] Does the hierarchy work?
- [ ] What needs further investigation or context?
- [ ] Any duplications?
- [ ] List any detailed metadata/methodology to add retrospectively
- [ ] Short metadata added

**Comment by Shannon95** [comment] 2020-04-20 15:01
Comments on issues fixed and what is remaining:

- Country code issue regarding the use of different codes for Serbia fixed and now matching what is used in the original source data (RS).

- Reference Period filter is now working fine. One aspect to note is the fact it is currently showing all reference periods available throughout Trade datasets and not only what is associated with the dataset in question. 

**BA Comments with response:** 
 _Only a generic email address in contact detail, whereas a specific contact name is present in airtable._  : Current limitation as the email is just scared at the moment, from my understanding this is being looked into for future dev. 

_No link available to the original website landing page._ : From my understanding this is currently not a feature. 

All technical issues noted fixed from a DE side and filter issues from Swirl side. Moving to **Needs Sign off.**

**Comment by JasonHowell** [comment] 2020-04-28 12:02
BA's have confirmed it is good to go in its current state.

**Comment by JasonHowell** [comment] 2020-05-18 10:52
Closing issue as now been deployed onto PMDv4.

**Comment by canwaf** [comment] 2020-11-26 17:18
Rewritten and simplified the mechanism to convert string periods using pandas' to_datetime functionality. Added the datamarker which is applicable for the entire dataset. N/A values left as is, and not defined in the datamarker field as why they are not applicable isn't defined within the dataset.

**Comment by LPerryman** [comment] 2021-01-13 14:23
Changed Marker to represent not-applicable for countries that data is not collected for and added more information to the metadata description. Published on PMD4 but probably needs changes to the metadata.

**Comment by LPerryman** [comment] 2021-01-19 11:23
PMD4
Trade in goods: all countries, seasonally adjusted
https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-sa-trade-in-goods-catalog-entry

**Comment by rossbowen** [comment] 2021-02-26 18:33
Build failing atm.

**Comment by mikeAdamss** [comment] 2021-02-27 09:56
was poking around the failed builds to make sure the databaker changes didn't break anything. though I'd leave a note on this this as its a confusing one due to the previous issues with the ONS scraper.

previously, the scraper was calling latest=True but essentially returning a random distribution, if you look here: https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-SA-Trade-in-goods/106/artifact/datasets/ONS-UK-SA-Trade-in-goods/out/trace.json (the build that actually worked) you can see from the `source` field that it was actually using the _oldest_ (v1) distribution of the data.

so the good news - it's bringing in the latest distribution properly now. The bad news - it's broke because the transform needs to be updated to work with the newer (and more complex) distribution.

**Comment by mikeAdamss** [comment] 2021-03-01 09:37
working now. Newest version of the data had data markers which the older script was unceremoniously dropping in the background (hence odd exceptions). The marker was `N/A` which I've taken as `not-applicable` but it should be easy to tweak if you're using something else these days.

**Closed** 2021-08-09 10:33 UTC
Labels: BA Review
